---

- hosts: leafs
  connection: local
  gather_facts: yes 

  vars_files:
  - "vars/main.yaml"

  tasks:

  - name: Configure Arista Vlans

    eos_config:

      src: templates/vlans.j2

      provider: "{{ eos_connection }}"  
